# ============================================
# FreeRADIUS Clients Configuration - Clinic
# ============================================

client clinic_network {
    ipaddr          = 192.168.0.0/16
    secret          = clinic_radius_secret
    shortname       = clinic
    nastype         = cisco
}

client admin_network {
    ipaddr          = 192.168.50.0/29
    secret          = admin_radius_secret
    shortname       = admin
}

client post_network {
    ipaddr          = 192.168.60.0/30
    secret          = post_radius_secret
    shortname       = post
}